import NavBar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[rgb(248,250,253)]`}
      >
        <NavBar />
        <div className="flex gap-20 me-8">
          <SideBar />
          <main className="bg-[rgb(255,255,255)] flex-1 rounded-4xl mt-4 p-7">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
